#!/bin/sh

dir="$(pwd)"
cd "$(dirname "$0")"
home="$(pwd)"
cd "${dir}"

host="${ZEL_HOST:-emacs -Q --batch}"
code="${ZEL_CODE:--l zel}"
debug="${ZEL_DEBUG:+-f toggle-debug-on-error}"

exec ${host} -L "${home}" ${code} ${debug} "$@"
